name: Build and Test (macOS)

on:
  workflow_dispatch: # manually trigger the workflow

permissions:
  checks: write
  actions: read
  contents: read

jobs:

  build-macos:
    name: macOS-Build (GLFW_GL3)
    runs-on: macos-15
    steps:

    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Configure and Build
      run: ${{github.workspace}}/build.sh

  build-tests-macos:
    name: macOS-Build (Tests)
    runs-on: macos-15

    env:
      PRESET_NAME: clang-macos-release
      CMAKE_CONFIG_OPTIONS: -DUSE_GLFW_GL3=0 -DUSE_GUI_TEST_ENGINE=1

    steps:

    - name: Checkout source code
      uses: actions/checkout@v5.0.0

    - name: Configure and Build
      run: |
        cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }} && \
        cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: |
        export GUI_TEST_MARKDOWN_REPORT_FILE=${{github.workspace}}/gui_test_report.md
        ${{github.workspace}}/build/release/bin/hello_gui
        cat $GUI_TEST_MARKDOWN_REPORT_FILE >> $GITHUB_STEP_SUMMARY
