name: GitHub Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch: # manually trigger the workflow

permissions:
  checks: write
  actions: read
  contents: read

jobs:

  build:
    name: Ubuntu-Build (GLFW_GL3)
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4.2.2

    - name: Install Linux Dependencies
      run: |
        sudo apt update
        sudo apt install  \
          libxrandr-dev   \
          libxinerama-dev \
          libxcursor-dev  \
          libxi-dev       \
          libgl-dev

    - name: Configure and Build
      run: ${{github.workspace}}/build.sh

  build-tests:
    name: Ubuntu-Build (Tests)
    runs-on: ubuntu-24.04

    env:
      PRESET_NAME: gcc-linux-release
      CMAKE_CONFIG_OPTIONS: -DUSE_GLFW_GL3=0 -DUSE_GUI_TEST_ENGINE=1

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4.2.2

    - name: Configure and Build
      run: |
        cmake --preset ${{ env.PRESET_NAME }} ${{ env.CMAKE_CONFIG_OPTIONS }} && \
        cmake --build --preset "${{ env.PRESET_NAME }}" -j

    - name: Run Tests
      run: |
        export GUI_TEST_MARKDOWN_REPORT_FILE=${{github.workspace}}/gui_test_report.md
        ${{github.workspace}}/build/release/bin/hello_gui
        cat $GUI_TEST_MARKDOWN_REPORT_FILE >> $GITHUB_STEP_SUMMARY
